# General
title: GovFresh
description: Government with and by the people.
url: https://govfresh.com

# Social
social:
  name: GovFresh
  links:
    - https://twitter.com/govfresh
    - https://www.facebook.com/govfresh
    - https://www.linkedin.com/company/govfresh
    - https://github.com/govfresh

twitter:
  username: GovFresh
  card: summary_large_image

# Build settings
theme:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

last-modified-at:
date-format: "%B %d, %Y at %I:%M %P %Z"

# Number limits
books-number: 7
dm-number: &dm-number 5
events-number: 4
innovations-number: 4
labs-number: 3
orgs-number: 4
podcasts-number: 4
reviews-number: &reviews-number 4
signal-number: &signal-number 2
thoughts-number: &thoughts-number 5

# Defaults
defaults:
  - scope:
      path: "_reviews"
      type: "reviews"
    values:
      folder: "Reviews"
      img-path: "books"
      parent: "reviews"
      layout: "review"
      short: "true"
  - scope:
      path: "_dm"
      type: "dm"
    values:
      folder: "Direct message"
      img-path: "people"
      parent: "dm"
      layout: "dm"
      short: "true"
  - scope:
      path: "_thoughts"
      type: "thoughts"
    values:
      folder: "Thoughts"
      img-path: "posts"
      parent: "thoughts"
      layout: "thoughts"
      short: "true"
  - scope:
      path: "_events"
      type: "events"
    values:
      folder: "Events"
      img-path: "events"
      parent: "events"
      layout: "profile"
      short: "true"
  - scope:
      path: "_books"
      type: "books"
    values:
      folder: "Book club"
      img-path: "books"
      parent: "books"
      layout: "profile"
      short: "true"
  - scope:
      path: "_orgs"
      type: "orgs"
    values:
      folder: "Organizations"
      img-path: "orgs"
      parent: "orgs"
      layout: "profile"
      short: "true"
  - scope:
      path: "_people"
      type: "people"
    values:
      folder: "Team"
      img-path: "people"
      parent: "team"
      layout: "people"
      short: "true"
  - scope:
      path: ""
      type: ""
    values:
      folder: ""
      img-path: ""
      parent: ""
      layout: "cards"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      folder: "Signal"
      img-path: "posts"
      parent: "signal"
      layout: "signal"
      short: "true"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: "_podcasts"
      type: "podcasts"
    values:
      folder: "Podcasts"
      img-path: "podcasts"
      parent: "podcasts"
      layout: "profile"
      short: "true"
  - scope:
      path: "_labs"
      type: "labs"
    values:
      folder: "Labs"
      img-path: "labs"
      parent: "labs"
      layout: "profile"
      short: "true"
  - scope:
      path: "_innovations"
      type: "innovations"
    values:
      folder: "Innovations"
      img-path: "innovations"
      parent: "innovations"
      layout: "profile"
      short: "true"
  - scope:
      path: ""
      type: ""
    values:
      folder: "Playlist"
      img-path:
      parent: "playlist"
      layout:
      short:

# Collections
collections:
  books:
    output: true
    permalink: /books/:title
  dm:
    output: true
    permalink: /dm/:title
  events:
    output: true
    permalink: /event/:title
  innovations:
    output: true
    permalink: innovations/:title
  labs:
    output: true
    permalink: labs/:title
  orgs:
    output: true
    permalink: /orgs/:title
  pages:
    output: true
    permalink: :title
  people:
    output: true
    permalink: people/:title
  podcasts:
    output: true
    permalink: podcasts/:title
  posts:
    output: true
    permalink: /signal/:title
  reviews:
    output: true
    permalink: /reviews/:title
  thoughts:
    output: true
    permalink: /thoughts/:title
  topics:
    output: true
    permalink: topics/:title

# Pagination
paginate: 12
paginate_path: "/signal/:num"

# Home page order
order:
  - 
    name: signal
    site-name: posts
    number: *signal-number  
  - 
    name: thoughts
    number: *thoughts-number
  - 
    name: dm
    number: *dm-number
  - 
    name: reviews
    number: *reviews-number

# Exclude
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
