# General
title: GovFresh
tagline: "Design. Technology. Democracy."
description: "Design. Technology. Democracy."
url: https://govfresh.com

# Social
social:
  name: GovFresh
  links:
    - https://twitter.com/govfresh
    - https://www.facebook.com/govfresh
    - https://www.linkedin.com/company/govfresh
    - https://github.com/govfresh

twitter-username: govfresh
twitter: "@govfresh"
linkedin: https://www.linkedin.com/company/govfresh

# Build settings
theme:
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-last-modified-at
  - jekyll-redirect-from

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

last-modified-at:
date-format: "%B %d, %Y at %I:%M %P %Z"

# 404
permalink: /404.html

# Number limits
books-number: 7
dm-number: &dm-number 5
labs-number: 3
podcast-number: &podcast-number 4
research-number: &research-number 4
thoughts-number: &thoughts-number 9

# Defaults
defaults:
  - scope:
      path: "_dm"
      type: "dm"
    values:
      folder: "Direct message"
      img-path: "people"
      parent: "dm"
      layout: "dm"
      short: "true"
      schematype: "Article"
  - scope:
      path: "_thoughts"
      type: "thoughts"
    values:
      folder: "Thoughts"
      img-path: "posts"
      parent: "thoughts"
      layout: "thoughts"
      short: "true"
      schematype: "NewsArticle"
  - scope:
      path: "_books"
      type: "books"
    values:
      folder: "Book club"
      img-path: "books"
      parent: "books"
      layout: "book"
      short: "true"
      schematype: "Book"
  - scope:
      path: "_research"
      type: "research"
    values:
      folder: "Research"
      img-path: "posts"
      parent: "research"
      layout: "research"
      short: "true"
      schematype: "NewsArticle"
  - scope:
      path: "_people"
      type: "people"
    values:
      folder: "Team"
      img-path: "people"
      parent: "team"
      layout: "people"
      short: "true"
      schematype: "ProfilePage"
  - scope:
      path: ""
      type: ""
    values:
      folder: ""
      img-path: ""
      parent: ""
      layout: "cards"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      folder: "Signal"
      img-path: "posts"
      parent: "signal"
      layout: "signal"
      short: "true"
      schematype: "NewsArticle"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: "_labs"
      type: "labs"
    values:
      folder: "Labs"
      img-path: "posts"
      parent: "labs"
      layout: "profile"
      short: "true"
  - scope:
      path: "_podcast"
      type: "podcast"
    values:
      folder: "Podcast"
      img-path: "people"
      parent: "podcast"
      layout: "podcast"
      short: "true"
      schematype: "PodcastSeries"

# Collections
collections:
  thoughts:
    output: true
    permalink: /thoughts/:title
  dm:
    output: true
    permalink: /dm/:title
  research:
    output: true
    permalink: /research/:title
  books:
    output: true
    permalink: /books/:title
  posts:
    output: true
    permalink: /signal/:title
  labs:
    output: true
    permalink: labs/:title
  pages:
    output: true
    permalink: :title
  people:
    output: true
    permalink: people/:title
  podcast:
    output: true
    permalink: podcast/:title
  topics:
    output: true
    permalink: topics/:title

# Pagination
paginate: 12
paginate_path: "/signal/:num"

# Home page order
order:
  - 
    name: thoughts
    number: *thoughts-number
  - 
    name: dm
    number: *dm-number
  - 
    name: research
    number: *research-number
  - 
    name: podcast
    number: *podcast-number
   
# Exclude
exclude:
  - gemfiles/
  - Gemfile
  - Gemfile.lock
